language: ruby
before_script:
  - psql -c 'create database queue_classic_test;' -U postgres
env:
  global:
    - QC_DATABASE_URL="postgres://postgres@localhost/queue_classic_test"
rvm:
  - 2.2.0
before_install:
  - gem update --system
addons:
  postgresql: 9.3
